### ISSUE TITLE
Model AI Website landing page 

### ISSUE THREAD

**Issue by athul-22** [PaulleDemon/awesome-landing-pages#1]

**Comment by PaulleDemon** [comment]
@athul-22 Hi, hope you're well. Can you provide or link a sample design? Currently this is the latest template [AISales App](https://aisales-app.netlify.app/) this not been put up on the website, but available on github at: https://github.com/PaulleDemon/landing-pages/blob/main/src/apps/AISales

**Comment by PaulleDemon** [comment]
Added new templates: https://ai-code.netlify.app/

Browse at: https://awesome-landingpages.vercel.app/

**Comment by athul-22** [comment]
Nice, bro... loved it
